CREATE TABLE users(
_id VARCHAR(36) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE,
password VARCHAR(255) NOT NULL,
date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP,
personalMsg VARCHAR(200),
img_url VARCHAR(200),
isAdmin BOOLEAN DEFAULT FALSE
) ENGINE=InnoDB;

ALTER TABLE users DROP COLUMN isConnected